input:
  postgres_listen:
    dsn: ${DSN}
    channel: ${CHANNEL}

pipeline:
  processors:
    - mutation: |
        root = "[%s @ %s]: %s".format(
          meta("pg_listen_channel"),
          meta("pg_listen_pid"),
          content()
        )

output:
  stdout: {}
