input:
  postgres_listen:
    dsn: ${DSN}
    channel: ${IN_CHANNEL}

pipeline:
  threads: 1
  processors:
    - mutation: |
        root = "[%s @ %s]: %s".format(
          meta("pg_listen_channel"),
          meta("pg_listen_pid"),
          this.message
        )

output:
  http_client:
    url: '${! env("MOCK_SERVER_BASE_URL") }/fail'
    verb: POST
    headers:
      Content-Type: application/json
    max_in_flight: 1
    retries: 1
