CREATE TABLE IF NOT EXISTS outbox_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP DEFAULT NOW(),
  payload JSON DEFAULT '{"message": "Hello, World!"}'::json,
  attempt_count INT DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE OR REPLACE FUNCTION notify_outbox_items_insert()
   RETURNS TRIGGER
   LANGUAGE plpgsql
AS $$
BEGIN
   PERFORM pg_notify('outbox_items__insert', NEW.payload::varchar);
   RETURN NULL;
END;
$$;

CREATE TRIGGER outbox_items__insert
AFTER INSERT ON outbox_items
REFERENCING NEW TABLE AS outbox_items__inserted
FOR EACH ROW
EXECUTE FUNCTION notify_outbox_items_insert();

-- throw a bunch of rows into the table!
-- INSERT INTO outbox_items SELECT id FROM generate_series(1, 101) AS g (id);
